### ISSUE TITLE
request.process_response is called twice if requestID not specified when job created

### ISSUE THREAD

**Issue by mwalsher** [skryl/qbwc#21]
I omitted the requestID since it is optional, but noticed that when I did so, my response handler was being called twice.

I traced the code quickly and it looks like it's being called once from receiveResponseXML() when the response is initialized (session.rb response=), and again from closeConnection().

I haven't been able to determine exactly why that's occurring, but hopefully this points you in the right direction.

**Comment by JasonBarnabe** [comment]
Closing this for now, if you can reproduce with the latest, create a new issue.
