### ISSUE TITLE
Intermittent ActionView::MissingTemplate in tests

### ISSUE THREAD

**Issue by rchekaluk** [skryl/qbwc#55]
When running the gem test suite using `rake test`, this intermittent error occurs occasionally:
```
ActionView::MissingTemplate (Missing template wash_with_soap/rpc/wsdl with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in:
):
  test/qbwc/integration/routes_test.rb:27:in `block in <class:RoutesTest>'
```

It's unclear how to reproduce this.

Intermittent errors like this can result from unintended interactions across different disparate test cases in the test suite.

I do note that a very similar error can be triggered by commenting out [prepend_view_path](https://github.com/skryl/qbwc/blob/master/test/qbwc/controllers/controller_test.rb#L13) and running a controller_test in isolation:
```
ruby test/qbwc/controllers/controller_test.rb -n test_authenticate_with_no_jobs
```

**Comment by JasonBarnabe** [comment]
Can't say I've ever seen that specific error, but I get this on every run:

```
  1) Failure:
RoutesTest#test_qbwc/action_without_soap_returns_successfully [/www/qbwc/test/qbwc/integration/routes_test.rb:26]:
Expected response to be a <success>, but was <500>
```
