### ISSUE TITLE
Logging can write sensitive information to logs

### ISSUE THREAD

**Issue by rchekaluk** [skryl/qbwc#62]
These log lines can potentially contain sensitive information; provide some way to mitigate that:
```
I, [2015-02-15T14:53:37.109829 #24529]  INFO -- : Requests available are '[{:customer_query_rq=>{:full_name=>"Quincy Bob William Carlos"}}]'.
```
```
I, [2015-02-15T14:53:37.132064 #24529]  INFO -- : Next request is '{:customer_query_rq=>{:full_name=>"Quincy Bob William Carlos"}}'.
```
```
I, [2015-02-15T15:32:19.189913 #24228]  INFO -- : Current request is <?xml version="1.0" encoding="utf-8"?>
```
```
I, [2015-02-15T15:00:47.076152 #31249]  INFO -- : Job 'integration_test' received response: '{"xml_attributes"=>{"statusCode"=>"0", "statusSeverity"=>"Info", "statusMessage"=>"Status OK"}, "customer_ret"=>{"xml_attributes"=>{}, "list_id"=>"8000001B-1405768916", "time_created"=>"2014-07-19T08:21:56-04:00", "time_modified"=>"2014-07-19T08:21:56-04:00", "edit_sequence"=>"1405768916", "name"=>"mrjoecustomer", "full_name"=>"Joseph Customer", "is_active"=>true, "sublevel"=>0, "company_name"=>"Joes Garage", "salutation"=>"Mr", "first_name"=>"Joe", "last_name"=>"Customer", "bill_address"=>{"xml_attributes"=>{}, "addr1"=>"123 Main St.", "city"=>"Mountain View", "state"=>"CA", "postal_code"=>"94566"}, "email"=>"joecustomer@gmail.com", "balance"=>0.0, "total_balance"=>0.0, "account_number"=>"89087", "credit_limit"=>2000.0, "job_status"=>"None"}}'.
```

The easiest approach would be to provide global configuration parameters (eg. `log_requests` and `log_responses`) that determines if these lines are logged (default `false` for production, default `true` for other Rails.env).

A more involved approach would be to mimic the Rails [filter_parameters](http://guides.rubyonrails.org/configuring.html#rails-general-configuration) technique, and scrub logged values based on their key.

Any thoughts and/or preferences?

**Comment by JasonBarnabe** [comment]
I think one param that determines whether the requests and responses are logged is logical. It would also be good to standardize what is logged and when. As you can see in your examples, sometimes it's the hash, sometimes it's the XML.
